import { lazy, Suspense } from "react";
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { AdminShell } from "./components/AdminShell";
import { ProtectedRoute } from "./components/ProtectedRoute";
import { PwaInstallPrompt } from "./components/PwaInstallPrompt";
import { AuthProvider } from "./contexts/AuthContext";
import { CartProvider } from "./contexts/CartContext";
const HomePage=lazy(()=>import("./pages/HomePage").then(m=>({default:m.HomePage})));const AuthPage=lazy(()=>import("./pages/AuthPage").then(m=>({default:m.AuthPage})));const CartPage=lazy(()=>import("./pages/CartPage").then(m=>({default:m.CartPage})));const CheckoutPage=lazy(()=>import("./pages/CheckoutPage").then(m=>({default:m.CheckoutPage})));const OrderDetailPage=lazy(()=>import("./pages/OrderDetailPage").then(m=>({default:m.OrderDetailPage})));const OrdersPage=lazy(()=>import("./pages/OrdersPage").then(m=>({default:m.OrdersPage})));const AdminCatalogPage=lazy(()=>import("./pages/admin/AdminCatalogPage").then(m=>({default:m.AdminCatalogPage})));const AdminDashboard=lazy(()=>import("./pages/admin/AdminDashboard").then(m=>({default:m.AdminDashboard})));const AdminDeliveriesPage=lazy(()=>import("./pages/admin/AdminDeliveriesPage").then(m=>({default:m.AdminDeliveriesPage})));const AdminNotificationsPage=lazy(()=>import("./pages/admin/AdminNotificationsPage").then(m=>({default:m.AdminNotificationsPage})));const AdminOrdersPage=lazy(()=>import("./pages/admin/AdminOrdersPage").then(m=>({default:m.AdminOrdersPage})));const AdminSettingsPage=lazy(()=>import("./pages/admin/AdminSettingsPage").then(m=>({default:m.AdminSettingsPage})));const AdminUsersPage=lazy(()=>import("./pages/admin/AdminUsersPage").then(m=>({default:m.AdminUsersPage})));const DriverPage=lazy(()=>import("./pages/driver/DriverPage").then(m=>({default:m.DriverPage})));
function Loader(){return <div className="screen-loader"><span/></div>}
function App(){return <BrowserRouter><AuthProvider><CartProvider><Suspense fallback={<Loader/>}><Routes><Route path="/" element={<HomePage/>}/><Route path="/connexion" element={<AuthPage/>}/><Route path="/panier" element={<CartPage/>}/><Route element={<ProtectedRoute roles={["CUSTOMER"]}/>}><Route path="/commande" element={<CheckoutPage/>}/><Route path="/orders" element={<OrdersPage/>}/><Route path="/orders/:reference" element={<OrderDetailPage/>}/></Route><Route element={<ProtectedRoute roles={["ADMIN"]}/>}><Route path="/admin" element={<AdminShell/>}><Route index element={<AdminDashboard/>}/><Route path="commandes" element={<AdminOrdersPage/>}/><Route path="catalogue" element={<AdminCatalogPage/>}/><Route path="livraisons" element={<AdminDeliveriesPage/>}/><Route path="clients" element={<AdminUsersPage/>}/><Route path="notifications" element={<AdminNotificationsPage/>}/><Route path="reglages" element={<AdminSettingsPage/>}/></Route></Route><Route element={<ProtectedRoute roles={["DELIVERER"]}/>}><Route path="/driver" element={<DriverPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Suspense></CartProvider></AuthProvider><PwaInstallPrompt/></BrowserRouter>}
export default App;
