import { Search } from "lucide-react";
import { useEffect, useState } from "react";
import { statusLabel } from "../../components/OrderStatus";
import { useAuth } from "../../contexts/AuthContext";
import { api, dateTime, money } from "../../lib/api";
import type { Order } from "../../lib/types";
const statuses=["","PENDING","CONFIRMED","PREPARING","READY","OUT_FOR_DELIVERY","DELIVERED","CANCELLED"];
const next:Record<string,string[]>={PENDING:["CONFIRMED","CANCELLED"],CONFIRMED:["PREPARING","CANCELLED"],PREPARING:["READY","CANCELLED"],READY:["OUT_FOR_DELIVERY","DELIVERED","CANCELLED"],OUT_FOR_DELIVERY:["DELIVERED"]};
export function AdminOrdersPage(){const{token}=useAuth();const[orders,setOrders]=useState<Order[]>([]);const[filter,setFilter]=useState("");const[search,setSearch]=useState("");const[error,setError]=useState("");const load=()=>api<{data:Order[]}>(`/admin/orders?page=1&limit=100${filter?`&status=${filter}`:""}${search?`&search=${encodeURIComponent(search)}`:""}`,{},token).then(r=>setOrders(r.data)).catch(e=>setError(e.message));useEffect(()=>{ void load(); },[filter]);const change=async(id:string,status:string)=>{try{await api(`/admin/orders/${id}/status`,{method:"PATCH",body:JSON.stringify({status})},token);load()}catch(e){setError(e instanceof Error?e.message:"Action impossible")}};return <div><div className="admin-page-head"><div><span className="eyebrow">Suivi opérationnel</span><h1>Commandes</h1><p>Traitez et faites avancer chaque commande.</p></div></div><div className="toolbar"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Référence, nom ou téléphone"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}>{statuses.map(s=><option value={s} key={s}>{s?statusLabel(s):"Tous les statuts"}</option>)}</select></div>{error&&<div className="error-banner">{error}</div>}<section className="panel no-pad"><div className="table-wrap"><table className="orders-table"><thead><tr><th>Commande</th><th>Client</th><th>Contenu</th><th>Total</th><th>Statut</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.reference}</b><small>{dateTime(o.createdAt)}</small></td><td>{o.customerName}<small>{o.customerPhone}</small></td><td>{o.items.map(i=>`${i.quantity}× ${i.productName}`).join(", ")}</td><td><b>{money(o.total)}</b></td><td><span className={`order-badge ${o.status.toLowerCase()}`}>{statusLabel(o.status)}</span></td><td>{next[o.status]?.length?<select defaultValue="" onChange={e=>{if(e.target.value)change(o.id,e.target.value)}}><option value="">Faire avancer…</option>{next[o.status].map(s=><option value={s} key={s}>{statusLabel(s)}</option>)}</select>:"—"}</td></tr>)}</tbody></table></div>{!orders.length&&<div className="panel-empty">Aucune commande pour ce filtre.</div>}</section></div>}
