import { Plus, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { api, dateTime } from "../../lib/api";
import { normalizePhone } from "../../lib/phone";
import type { User, UserRole } from "../../lib/types";
interface AdminUser extends User {isActive:boolean;createdAt:string;lastLoginAt?:string}
export function AdminUsersPage(){const{token}=useAuth();const[users,setUsers]=useState<AdminUser[]>([]);const[show,setShow]=useState(false);const[error,setError]=useState("");const load=()=>api<AdminUser[]>("/admin/users",{},token).then(setUsers);useEffect(()=>{load()},[token]);const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);await api("/admin/users",{method:"POST",body:JSON.stringify({displayName:d.get("name"),email:d.get("email")||undefined,phone:d.get("phone")?normalizePhone(String(d.get("phone"))):undefined,role:"DELIVERER"})},token).then(()=>{setShow(false);load()},(reason:unknown)=>setError(reason instanceof Error?reason.message:"Création impossible."))};const toggle=async(u:AdminUser)=>{await api(`/admin/users/${u.id}`,{method:"PATCH",body:JSON.stringify({isActive:!u.isActive})},token);load()};return <div><div className="admin-page-head"><div><span className="eyebrow">Comptes</span><h1>Utilisateurs</h1><p>Clients, livreurs et administrateurs.</p></div><button className="button primary" onClick={()=>{setError("");setShow(true)}}><Plus/> Inviter un livreur</button></div><section className="panel no-pad"><div className="table-wrap"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Création</th><th>État</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="user-cell"><span><UserRound/></span><div><b>{u.displayName}</b><small>{[u.phone,u.email].filter(Boolean).join(" · ")}</small></div></div></td><td>{({ADMIN:"Administratrice",DELIVERER:"Livreur",CUSTOMER:"Client"} as Record<UserRole,string>)[u.role]}</td><td>{dateTime(u.createdAt)}</td><td><span className={u.isActive?"active-dot":"inactive-dot"}>{u.isActive?"Actif":"Désactivé"}</span></td><td>{u.role!=="ADMIN"&&<button className="text-button" onClick={()=>toggle(u)}>{u.isActive?"Désactiver":"Réactiver"}</button>}</td></tr>)}</tbody></table></div></section>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><span className="eyebrow">Équipe</span><h2>Inviter un livreur</h2><p>Il se connectera par code SMS avec ce numéro. L’e-mail est facultatif.</p><form onSubmit={create}><label>Nom<input name="name" required/></label><label>Téléphone<input name="phone" type="tel" required placeholder="6 90 00 00 00"/></label><label>E-mail (facultatif)<input name="email" type="email"/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary wide">Créer l’invitation</button></form></div></div>}</div>}
